export enum adminListConstants {
    ADMIN_LIST_BEGIN = 'ADMIN_LIST_BEGIN',
    ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS',
    ADMIN_LIST_ERROR = 'ADMIN_LIST_ERROR',

    ADMIN_SEARCH_BEGIN = 'ADMIN_SEARCH_BEGIN',
    ADMIN_SEARCH_SUCCESS = 'ADMIN_SEARCH_SUCCESS',
    ADMIN_SEARCH_ERROR = 'ADMIN_SEARCH_ERROR'
}