export enum teacherListConstants {
    TEACHER_LIST_BEGIN = 'TEACHER_LIST_BEGIN',
    TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS',
    TEACHER_LIST_ERROR = 'TEACHER_LIST_ERROR',

    TEACHER_SEARCH_BEGIN = 'TEACHER_SEARCH_BEGIN',
    TEACHER_SEARCH_SUCCESS = 'TEACHER_SEARCH_SUCCESS',
    TEACHER_SEARCH_ERROR = 'TEACHER_SEARCH_ERROR'
}